//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

using System.Xml.Serialization;

namespace CommandRunner.XML_Schemas {
	/// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://samrueby.com")]
    [XmlRoot("systemDevelopmentConfiguration", Namespace="http://samrueby.com", IsNullable=false)]
    public partial class SystemDevelopmentConfiguration {
        
        private string libraryNamespaceAndAssemblyNameField;
        
        private DatabaseConfiguration databaseConfigurationField;
        
        private Database databaseField;
        
        /// <remarks/>
        public string LibraryNamespaceAndAssemblyName {
            get {
                return this.libraryNamespaceAndAssemblyNameField;
            }
            set {
                this.libraryNamespaceAndAssemblyNameField = value;
            }
        }
        
        /// <remarks/>
        public DatabaseConfiguration databaseConfiguration {
            get {
                return this.databaseConfigurationField;
            }
            set {
                this.databaseConfigurationField = value;
            }
        }
        
        /// <remarks/>
        public Database database {
            get {
                return this.databaseField;
            }
            set {
                this.databaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [XmlInclude(typeof(OracleDatabase))]
    [XmlInclude(typeof(MySqlDatabase))]
    [XmlInclude(typeof(SqlServerDatabase))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://samrueby.com")]
    public abstract partial class DatabaseConfiguration {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://samrueby.com")]
    public partial class CustomModification {
        
        private string nameField;
        
        private string[] commandsField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("command", IsNullable=false)]
        public string[] commands {
            get {
                return this.commandsField;
            }
            set {
                this.commandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://samrueby.com")]
    public partial class Query {
        
        private string selectFromClauseField;
        
        private QueryPostSelectFromClause[] postSelectFromClausesField;
        
        private string nameField;
        
        /// <remarks/>
        public string selectFromClause {
            get {
                return this.selectFromClauseField;
            }
            set {
                this.selectFromClauseField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("postSelectFromClause", IsNullable=false)]
        public QueryPostSelectFromClause[] postSelectFromClauses {
            get {
                return this.postSelectFromClausesField;
            }
            set {
                this.postSelectFromClausesField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://samrueby.com")]
    public partial class QueryPostSelectFromClause {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://samrueby.com")]
    public partial class RowConstantTable {
        
        private string tableNameField;
        
        private string valueColumnField;
        
        private string nameColumnField;
        
        private string orderByColumnField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string tableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string valueColumn {
            get {
                return this.valueColumnField;
            }
            set {
                this.valueColumnField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string nameColumn {
            get {
                return this.nameColumnField;
            }
            set {
                this.nameColumnField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string orderByColumn {
            get {
                return this.orderByColumnField;
            }
            set {
                this.orderByColumnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://samrueby.com")]
    public partial class Database {
        
        private string[] whitelistedTablesField;
        
        private RowConstantTable[] rowConstantTablesField;
        
        private string[] smallTablesField;
        
        private string[] tablesUsingRowVersionedDataCachingField;
        
        private string[] revisionHistoryTablesField;
        
        private Query[] queriesField;
        
        private CustomModification[] customModificationsField;
        
        /// <remarks/>
        [XmlArrayItem("Table", IsNullable=false)]
        public string[] WhitelistedTables {
            get {
                return this.whitelistedTablesField;
            }
            set {
                this.whitelistedTablesField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("table", IsNullable=false)]
        public RowConstantTable[] rowConstantTables {
            get {
                return this.rowConstantTablesField;
            }
            set {
                this.rowConstantTablesField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("Table", IsNullable=false)]
        public string[] SmallTables {
            get {
                return this.smallTablesField;
            }
            set {
                this.smallTablesField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("Table", IsNullable=false)]
        public string[] TablesUsingRowVersionedDataCaching {
            get {
                return this.tablesUsingRowVersionedDataCachingField;
            }
            set {
                this.tablesUsingRowVersionedDataCachingField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("table", IsNullable=false)]
        public string[] revisionHistoryTables {
            get {
                return this.revisionHistoryTablesField;
            }
            set {
                this.revisionHistoryTablesField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("query", IsNullable=false)]
        public Query[] queries {
            get {
                return this.queriesField;
            }
            set {
                this.queriesField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("modification", IsNullable=false)]
        public CustomModification[] customModifications {
            get {
                return this.customModificationsField;
            }
            set {
                this.customModificationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://samrueby.com")]
    public partial class SqlServerAuthenticationLogin {
        
        private string loginNameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string LoginName {
            get {
                return this.loginNameField;
            }
            set {
                this.loginNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://samrueby.com")]
    public partial class OracleDatabase : DatabaseConfiguration {
        
        private string tnsNameField;
        
        private string userAndSchemaField;
        
        private string passwordField;
        
        private bool supportsConnectionPoolingField;
        
        private bool supportsConnectionPoolingFieldSpecified;
        
        private bool supportsLinguisticIndexesField;
        
        private bool supportsLinguisticIndexesFieldSpecified;
        
        /// <remarks/>
        public string tnsName {
            get {
                return this.tnsNameField;
            }
            set {
                this.tnsNameField = value;
            }
        }
        
        /// <remarks/>
        public string userAndSchema {
            get {
                return this.userAndSchemaField;
            }
            set {
                this.userAndSchemaField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public bool SupportsConnectionPooling {
            get {
                return this.supportsConnectionPoolingField;
            }
            set {
                this.supportsConnectionPoolingField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool SupportsConnectionPoolingSpecified {
            get {
                return this.supportsConnectionPoolingFieldSpecified;
            }
            set {
                this.supportsConnectionPoolingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool SupportsLinguisticIndexes {
            get {
                return this.supportsLinguisticIndexesField;
            }
            set {
                this.supportsLinguisticIndexesField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool SupportsLinguisticIndexesSpecified {
            get {
                return this.supportsLinguisticIndexesFieldSpecified;
            }
            set {
                this.supportsLinguisticIndexesFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://samrueby.com")]
    public partial class MySqlDatabase : DatabaseConfiguration {
        
        private string databaseField;
        
        /// <remarks/>
        public string database {
            get {
                return this.databaseField;
            }
            set {
                this.databaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://samrueby.com")]
    public partial class SqlServerDatabase : DatabaseConfiguration {
        
        private string serverField;
        
        private SqlServerAuthenticationLogin sqlServerAuthenticationLoginField;
        
        private string databaseField;
        
        private string fullTextCatalogField;
        
        /// <remarks/>
        public string server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
            }
        }
        
        /// <remarks/>
        public SqlServerAuthenticationLogin SqlServerAuthenticationLogin {
            get {
                return this.sqlServerAuthenticationLoginField;
            }
            set {
                this.sqlServerAuthenticationLoginField = value;
            }
        }
        
        /// <remarks/>
        public string database {
            get {
                return this.databaseField;
            }
            set {
                this.databaseField = value;
            }
        }
        
        /// <remarks/>
        public string FullTextCatalog {
            get {
                return this.fullTextCatalogField;
            }
            set {
                this.fullTextCatalogField = value;
            }
        }
    }
}
