//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace TypedDataLayer {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samrueby.com")]
    [System.Xml.Serialization.XmlRootAttribute("systemDevelopmentConfiguration", Namespace="http://samrueby.com", IsNullable=false)]
    public partial class SystemDevelopmentConfiguration {
        
        private string libraryNamespaceAndAssemblyNameField;
        
        private DatabaseConfiguration databaseConfigurationField;
        
        private Database databaseField;
        
        /// <remarks/>
        public string LibraryNamespaceAndAssemblyName {
            get {
                return this.libraryNamespaceAndAssemblyNameField;
            }
            set {
                this.libraryNamespaceAndAssemblyNameField = value;
            }
        }
        
        /// <remarks/>
        public DatabaseConfiguration databaseConfiguration {
            get {
                return this.databaseConfigurationField;
            }
            set {
                this.databaseConfigurationField = value;
            }
        }
        
        /// <remarks/>
        public Database database {
            get {
                return this.databaseField;
            }
            set {
                this.databaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OracleDatabase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MySqlDatabase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SqlServerDatabase))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samrueby.com")]
    public abstract partial class DatabaseConfiguration {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samrueby.com")]
    public partial class CustomModification {
        
        private string nameField;
        
        private string[] commandsField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("command", IsNullable=false)]
        public string[] commands {
            get {
                return this.commandsField;
            }
            set {
                this.commandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samrueby.com")]
    public partial class Query {
        
        private string selectFromClauseField;
        
        private QueryPostSelectFromClause[] postSelectFromClausesField;
        
        private string nameField;
        
        /// <remarks/>
        public string selectFromClause {
            get {
                return this.selectFromClauseField;
            }
            set {
                this.selectFromClauseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("postSelectFromClause", IsNullable=false)]
        public QueryPostSelectFromClause[] postSelectFromClauses {
            get {
                return this.postSelectFromClausesField;
            }
            set {
                this.postSelectFromClausesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://samrueby.com")]
    public partial class QueryPostSelectFromClause {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samrueby.com")]
    public partial class RowConstantTable {
        
        private string tableNameField;
        
        private string valueColumnField;
        
        private string nameColumnField;
        
        private string orderByColumnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valueColumn {
            get {
                return this.valueColumnField;
            }
            set {
                this.valueColumnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nameColumn {
            get {
                return this.nameColumnField;
            }
            set {
                this.nameColumnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string orderByColumn {
            get {
                return this.orderByColumnField;
            }
            set {
                this.orderByColumnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samrueby.com")]
    public partial class Database {
        
        private int commandTimeoutSecondsField;
        
        private bool commandTimeoutSecondsFieldSpecified;
        
        private string[] whitelistedTablesField;
        
        private RowConstantTable[] rowConstantTablesField;
        
        private string[] smallTablesField;
        
        private string[] tablesUsingRowVersionedDataCachingField;
        
        private string[] revisionHistoryTablesField;
        
        private Query[] queriesField;
        
        private CustomModification[] customModificationsField;
        
        /// <remarks/>
        public int CommandTimeoutSeconds {
            get {
                return this.commandTimeoutSecondsField;
            }
            set {
                this.commandTimeoutSecondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommandTimeoutSecondsSpecified {
            get {
                return this.commandTimeoutSecondsFieldSpecified;
            }
            set {
                this.commandTimeoutSecondsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Table", IsNullable=false)]
        public string[] WhitelistedTables {
            get {
                return this.whitelistedTablesField;
            }
            set {
                this.whitelistedTablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("table", IsNullable=false)]
        public RowConstantTable[] rowConstantTables {
            get {
                return this.rowConstantTablesField;
            }
            set {
                this.rowConstantTablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Table", IsNullable=false)]
        public string[] SmallTables {
            get {
                return this.smallTablesField;
            }
            set {
                this.smallTablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Table", IsNullable=false)]
        public string[] TablesUsingRowVersionedDataCaching {
            get {
                return this.tablesUsingRowVersionedDataCachingField;
            }
            set {
                this.tablesUsingRowVersionedDataCachingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("table", IsNullable=false)]
        public string[] revisionHistoryTables {
            get {
                return this.revisionHistoryTablesField;
            }
            set {
                this.revisionHistoryTablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("query", IsNullable=false)]
        public Query[] queries {
            get {
                return this.queriesField;
            }
            set {
                this.queriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("modification", IsNullable=false)]
        public CustomModification[] customModifications {
            get {
                return this.customModificationsField;
            }
            set {
                this.customModificationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samrueby.com")]
    public partial class OracleDatabase : DatabaseConfiguration {
        
        private string connectionStringField;
        
        private bool supportsLinguisticIndexesField;
        
        private bool supportsLinguisticIndexesFieldSpecified;
        
        /// <remarks/>
        public string ConnectionString {
            get {
                return this.connectionStringField;
            }
            set {
                this.connectionStringField = value;
            }
        }
        
        /// <remarks/>
        public bool SupportsLinguisticIndexes {
            get {
                return this.supportsLinguisticIndexesField;
            }
            set {
                this.supportsLinguisticIndexesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SupportsLinguisticIndexesSpecified {
            get {
                return this.supportsLinguisticIndexesFieldSpecified;
            }
            set {
                this.supportsLinguisticIndexesFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samrueby.com")]
    public partial class MySqlDatabase : DatabaseConfiguration {
        
        private string connectionStringField;
        
        /// <remarks/>
        public string ConnectionString {
            get {
                return this.connectionStringField;
            }
            set {
                this.connectionStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samrueby.com")]
    public partial class SqlServerDatabase : DatabaseConfiguration {
        
        private string connectionStringField;
        
        /// <remarks/>
        public string ConnectionString {
            get {
                return this.connectionStringField;
            }
            set {
                this.connectionStringField = value;
            }
        }
    }
}
